### ISSUE TITLE
Cant Print

### ISSUE THREAD

**Issue by Boledy** [MicrosoftDocs/OfficeEDU#10]
Printing seems to be disabled on the document.  I would normally print this content to my OneNote but am having to screen clip instead.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3cd06251-add0-4d3a-52a1-b82219e4f95a
* Version Independent ID: 846b813d-b7e9-c7e3-fd9a-594edbcefd92
* Content: [Term Transition and Expired Class Management](https://docs.microsoft.com/en-us/schooldatasync/sds-term-transition-and-expired-class-management#feedback)
* Content Source: [SchoolDataSync/SDS-term-transition-and-expired-class-management.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/SDS-term-transition-and-expired-class-management.md)
* Service: **school-data-sync**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
Closing as feedback is not actionable and was submitted several months ago.
