### ISSUE TITLE
Incorrect link in Post Set-up Tasks

### ISSUE THREAD

**Issue by MCPDev-James** [MicrosoftDocs/OfficeEDU#11]
The link titled "Click here to find out how to monitor CSV sync automation" (https://docs.microsoft.com/en-us/schooldatasync/monitor-csv-sync-automation) does not lead to a valid document.

I believe this one is the correct URL: https://docs.microsoft.com/en-us/schooldatasync/monitoring-csv-sync-automation

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8dc1ec98-4577-2c6d-12fd-94f3bbbe9b00
* Version Independent ID: 7a84cc02-2260-8390-6ced-468ddcd7dd22
* Content: [Set up your SDS Flow](https://docs.microsoft.com/en-us/schooldatasync/set-up-your-sds-flow)
* Content Source: [SchoolDataSync/Set-up-your-SDS-Flow.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/Set-up-your-SDS-Flow.md)
* Service: **school-data-sync**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
Thank you for catching this. The link has been updated.
