### ISSUE TITLE
No spaces are allowed in the Section ID's

### ISSUE THREAD

**Issue by turpie** [MicrosoftDocs/OfficeEDU#12]
Note that spaces are not allowed in the Section ID's, even though they aren't listed in the invalid characters documentation.
In our SIS we use alphanumeric Class Codes with spaces. e.g. 'DRA 8V' = Drama for 8V
These needed to be removed from the CSV files before they would import.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfc9a32c-41ae-553a-ab3c-d4437915cfce
* Version Independent ID: 4c0e5540-fe08-a3ee-2cde-87444746efe5
* Content: [CSV files for School Data Sync](https://docs.microsoft.com/en-us/schooldatasync/csv-files-for-school-data-sync#sectioncsv)
* Content Source: [SchoolDataSync/csv-files-for-school-data-sync.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/csv-files-for-school-data-sync.md)
* Service: **school-data-sync**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
My apologies for the delay. The page mentioned has been repurposed however we have updated our additional documentation to reflect this. Thank you for catching this and letting us know.
