### ISSUE TITLE
Awards

### ISSUE THREAD

**Issue by Global0823** [MicrosoftDocs/OfficeEDU#13]
Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f27df010-2d23-0846-e9de-2f9507b2583e
* Version Independent ID: f621e160-74e7-e3a6-4394-f70f18e5b898
* Content: [Create your office 365 tenant](https://docs.microsoft.com/en-us/microsoft-365/education/deploy/create-your-office-365-tenant)
* Content Source: [M365Education/deploy/create-your-office-365-tenant.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/M365Education/deploy/create-your-office-365-tenant.md)
* Service: **microsoft-365-education**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
Closing as Feedback isn't actionable
