### ISSUE TITLE
Please update list of SIS Vendors

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/OfficeEDU#14]
See https://docs.microsoft.com/en-us/schooldatasync/whats-new-with-school-data-sync#january-2019 for added support.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13884a06-3bba-06c2-82d6-45821beea8fc
* Version Independent ID: 15f171e5-227e-4e67-f2a8-72588cc4fd71
* Content: [OneRoster® Partner API Guidance](https://docs.microsoft.com/en-us/schooldatasync/oneroster-partner-api-guidance-1#feedback)
* Content Source: [SchoolDataSync/oneroster-partner-api-guidance-1.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/oneroster-partner-api-guidance-1.md)
* Service: **school-data-sync**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
Hello! Thank you letting us know. We are constantly working towards integrating more partners however it is up to the partners to create the OneRoster connection.
Closing feedback as it is unactionable.
