### ISSUE TITLE
Step 12 - Your NOT You're (you are)

### ISSUE THREAD

**Issue by ChrisMSNT** [MicrosoftDocs/OfficeEDU#15]
Replace You're for Your in Step 12. (curban@microsoft.com)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f27df010-2d23-0846-e9de-2f9507b2583e
* Version Independent ID: f621e160-74e7-e3a6-4394-f70f18e5b898
* Content: [Create your office 365 tenant](https://docs.microsoft.com/en-us/microsoft-365/education/deploy/create-your-office-365-tenant#feedback)
* Content Source: [M365Education/deploy/create-your-office-365-tenant.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/M365Education/deploy/create-your-office-365-tenant.md)
* Service: **microsoft-365-education**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
Hello! Thank you for catching this for us! Unfortunately the Microsoft 365 Education repro is without a manager so we will not be able to update this page until a new one gets appointed.
Because this repro is no longer being monitored for updates I am closing this issue.
