### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by hoyty76** [MicrosoftDocs/OfficeEDU#16]
Since this is being discontinued at end of month might want to note that

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 64527e9d-b3a9-d985-ac17-2e4265c91b36
* Version Independent ID: ca686516-b903-8794-35e6-9c0d33de374c
* Content: [Use Education Resources](https://docs.microsoft.com/en-us/microsoft-365/education/deploy/use-education-resources)
* Content Source: [M365Education/deploy/use-education-resources.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/M365Education/deploy/use-education-resources.md)
* Service: **microsoft-365-education**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
Hello! Thank you for mentioning this. Yes it is true that this site is no longer going to be managed but we are still going to keep this site as we hope to keep this project in the future.
