### ISSUE TITLE
"What apps work with School Data sync?" section needs improvement.

### ISSUE THREAD

**Issue by Word66** [MicrosoftDocs/OfficeEDU#17]
The entire section is two sentences. The first is ambiguous and reads like marketing, and the second is false (no apps listed anywhere at the linked site).
It needs some work.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b6f010e-cefc-d76e-690b-c08e63c5ce2a
* Version Independent ID: ffad0cad-8935-c8dc-38c1-fe45783bf9bd
* Content: [Frequently Asked Questions](https://docs.microsoft.com/en-us/schooldatasync/frequently-asked-questions#what-apps-work-with-school-data-sync)
* Content Source: [SchoolDataSync/frequently-asked-questions.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/frequently-asked-questions.md)
* Service: **school-data-sync**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by Word66** [comment]
See also:
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5fca7ab6-6e03-3319-1c82-4e9e17165781
* Version Independent ID: bce3fbb6-e1d6-e627-2057-426d11a0dcb5
* Content: [What apps work with School Data sync](https://docs.microsoft.com/en-us/schooldatasync/what-apps-work-with-school-data-sync)
* Content Source: [SchoolDataSync/what-apps-work-with-school-data-sync.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/what-apps-work-with-school-data-sync.md)
* Service: **school-data-sync**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
Hello! My apologies about the delay. We are currently working on overhauling numerous pages of our Docs site to ensure they make sense and provide accurate, and where necessary, in-depth information. While we would like to link directly to the list of applications that use O365 and SDS, it is not possible. The page is referencing the "Featured Apps" section at the top. Please see attached screenshot for clarification on the location.
![2019-04-17 131510](https://user-images.githubusercontent.com/48929578/56609758-84add380-65d3-11e9-9acf-37f92d58bade.png)
