### ISSUE TITLE
What is Classroom?

### ISSUE THREAD

**Issue by cdsmythe** [MicrosoftDocs/OfficeEDU#19]
This page references Classroom - is this a former Microsoft product or a third party SIS app? I think it needs clarification.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c13b1096-7005-2f9d-3807-e8a692a3ffe2
* Version Independent ID: 5982ceab-bd84-fe7d-f719-d94d177f4c2a
* Content: [If we remove a user or section from Classroom will they reappear when we sync again](https://docs.microsoft.com/en-us/schooldatasync/if-we-remove-a-user-or-section-from-classroom-will-they-reappear-when-we-sync-again#feedback)
* Content Source: [SchoolDataSync/if-we-remove-a-user-or-section-from-Classroom-will-they-reappear-when-we-sync-again.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/if-we-remove-a-user-or-section-from-Classroom-will-they-reappear-when-we-sync-again.md)
* Service: **school-data-sync**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
Hello @cdsmythe. My apologies about the delay. Microsoft Classroom was sort of the first incarnation of SDS and Microsoft Teams. The page mentioned is out of date and we are in the process of removing it to avoid any further confusion.
