### ISSUE TITLE
Mistake in number of solutions

### ISSUE THREAD

**Issue by mrpapercut** [MicrosoftDocs/OfficeEDU#2]
ClassLink, Infinite Campus, Focus School Software and Capita makes 4, not 3, solutions.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cb662b40-266f-0e8a-d44b-97186fa2861a
* Version Independent ID: e3167130-a80a-8223-33cb-1c928f85e129
* Content: [Frequently Asked Questions](https://docs.microsoft.com/en-us/schooldatasync/what-sises-are-supported-by-oneroster-api-connector)
* Content Source: [SchoolDataSync/what-SISes-are-supported-by-oneroster-API-connector.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/what-SISes-are-supported-by-oneroster-API-connector.md)
* Service: **school-data-sync**
* GitHub Login: @LaurenMoynihan
* Microsoft Alias: **SDSSupport**

**Comment by LaurenMoynihan** [comment]
Thanks, I removed the number since we will continue to add partners.
