### ISSUE TITLE
UK Addresses do not include States or ZIP codes and as for the Country code, is this some 'made up stuff' as it does not relate to any code for the UK that I am aware of

### ISSUE THREAD

**Issue by pcarlson1952** [MicrosoftDocs/OfficeEDU#21]
UK Addresses do not include States or ZIP codes and as for the Country code, is this some 'made up stuff' as it does not relate to any code for the UK that I am aware of, it appears to be the zip code for Redmond.  I do not understand why passwords would be required as logon is via AD, and I don't think I'm really expected (or able) to get everybody's password, this does not make sense.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: bfc9a32c-41ae-553a-ab3c-d4437915cfce
* Version Independent ID: 4c0e5540-fe08-a3ee-2cde-87444746efe5
* Content: [CSV files for School Data Sync](https://docs.microsoft.com/en-us/schooldatasync/csv-files-for-school-data-sync)
* Content Source: [SchoolDataSync/csv-files-for-school-data-sync.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/csv-files-for-school-data-sync.md)
* Service: **school-data-sync**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
Hello! Thank you very much for your feedback. Unfortunately the file headers are required for SDS to populate the additional information. While the State and Zip code headers are required, the information within can be a String and does not have to conform to the US address/postal system.
Passwords are a required field only if you are utilizing SDS to populate an Azure AD environment. If there are already users that have been created, you can leave the Password, First Name, and Last Name fields blank and still sync.
If you have any other questions regarding this please feel free to create a support ticket at aka.ms/sdssupport or reach out to your deployment manager.
Dan Baumgartner | Deployment Manager
