### ISSUE TITLE
[LOC] Invalid link in an article

### ISSUE THREAD

**Issue by OfficeGlobal** [MicrosoftDocs/OfficeEDU#22]
There is an invalid link redirecting to non existing page.

**Repro steps**:
1. Go to https://docs.microsoft.com/en-us/SchoolDataSync/how-to-deploy-school-data-sync-by-using-powerschool-sync
2. Search for "https://Powerschool.com/public/"
3. Click on the link

**Actual results**:
Link is broken
**Expected results**:
Link should be redirecting correctly or removed from the page

**GH article**:
https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/how-to-deploy-school-data-sync-by-using-powerschool-sync.md

![image](https://user-images.githubusercontent.com/47977325/59269633-d24bd180-8c4f-11e9-8270-a04755f3eca9.png)

**Comment by DanBaumgartner** [comment]
The link highlighted is an example to show that the schools who deploy with PowerSchool API should confirm that the endpoints are set correctly. They are not intended to be valid links.
