### ISSUE TITLE
Misspelling - 2. Office 365 Poweershell

### ISSUE THREAD

**Issue by ChrisMSNT** [MicrosoftDocs/OfficeEDU#24]
Correction: Office 365 PowerShell

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddc00bca-f247-11e9-c187-987390e8b67e
* Version Independent ID: 8c6c03f0-2172-2ed0-f540-b047617726f5
* Content: [License Users](https://docs.microsoft.com/en-us/microsoft-365/education/deploy/license-users#feedback)
* Content Source: [M365Education/deploy/license-users.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/M365Education/deploy/license-users.md)
* Service: **microsoft-365-education**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
This has been corrected.
