### ISSUE TITLE
Step 1: Deploy Windows 10 Tree Navigation

### ISSUE THREAD

**Issue by ChrisMSNT** [MicrosoftDocs/OfficeEDU#26]
Under Phase 2, it has Step 1: Deploy Windows 10 and Step 2: Manage devices with Intune for Education(this page). However, Step 1 in the tree has the same nested entry. It seems like someone forgot to remove the link? Additionally, that link refers to a historical page that's a MESS of navigation, links and such. curban@microsoft.com

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d32d5625-ad3a-86d1-5526-e31003ce2efb
* Version Independent ID: b5bd1f84-fe9f-fb6d-2e9f-09b0b8d5a3c1
* Content: [Intune for Education](https://docs.microsoft.com/en-us/microsoft-365/education/deploy/intune-for-education)
* Content Source: [M365Education/deploy/Intune-for-Education.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/M365Education/deploy/Intune-for-Education.md)
* Service: **microsoft-365-education**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by LaurenMoynihan** [comment]
For some reason I never received this message.  Someone else did and just forwarded it to me today.  We have changed the navigation around since you commented.  Which URL is the one with the mess of navigation?

**Comment by DanBaumgartner** [comment]
Closing as there hasn't been any activity. From previous changes this should be addressed. Please let up know if it is not.
