### ISSUE TITLE
No roadmap updates?

### ISSUE THREAD

**Issue by KohnAlexander** [MicrosoftDocs/OfficeEDU#27]
Not updated for 1,5 years?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1955a800-a939-e63c-6ef9-854210b4377e
* Version Independent ID: 007e8077-edee-b28d-91dd-8c11aa42ed1f
* Content: [SDS Roadmap](https://docs.microsoft.com/en-us/schooldatasync/sds-roadmap#feedback)
* Content Source: [SchoolDataSync/SDS-roadmap.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/SDS-roadmap.md)
* Service: **school-data-sync**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
Hello!

Thank you for your question! We actually update the Road-map for SDS whenever we have new information about upcoming features that we can share with the community.

The date on the page, 4/14/18, is actually not the last time it was updated but rather when the page was first published. The last update to the Road-map was actually updated last month when we had released the Targeted Cleanup option.

Please let me know if there are any other questions about this or if i may close this issue.

Dan Baumgartner | SDS Deployment Manager

**Comment by DanBaumgartner** [comment]
Hello!

As there hasn't been any reply in a week i am closing this notice. If there are any other questions please let us know.

Dan Baumgartner | SDS Deployment Manager
