### ISSUE TITLE
Education Attribute Refence location

### ISSUE THREAD

**Issue by jmthia** [MicrosoftDocs/OfficeEDU#4]
hello,
Can you add a link to the Education Attributes Reference ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: dc10ddc8-9da7-ba94-bb33-61660cca15c5
* Version Independent ID: 8b49e358-d402-4361-9c95-a93024fcdc7f
* Content: [What is the School Data Sync schema (object and attributes) available through REST API](https://docs.microsoft.com/en-us/schooldatasync/what-is-the-school-data-sync-schema-available-through-rest-api)
* Content Source: [SchoolDataSync/What-is-the-School-Data-Sync-schema-available-through-REST-API.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/What-is-the-School-Data-Sync-schema-available-through-REST-API.md)
* Service: **school-data-sync**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by kenwith** [comment]
@jmthia - I submitted a Pull Request to add a link to he attributes. They appear in the CSV section. I don't have permissions to merge but will keep an eye for when it is approved. Thanks for feedback!
