### ISSUE TITLE
Link is broken  "For all SDS scripts, please see this page"

### ISSUE THREAD

**Issue by nimojg-microsoft** [MicrosoftDocs/OfficeEDU#5]
Gives me a 404

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5c117f41-ce89-d8fb-29c4-f3d3aa142a1c
* Version Independent ID: 96506c01-6990-a9f4-f00b-a5e623783f93
* Content: [ms.date: 04/15/2018](https://docs.microsoft.com/en-us/schooldatasync/school-data-sync-powershell)
* Content Source: [SchoolDataSync/School-Data-Sync-Powershell.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/School-Data-Sync-Powershell.md)
* Service: **school-data-sync**
* GitHub Login: @LaurenMoynihan
* Microsoft Alias: **SDSSupport**

**Comment by LaurenMoynihan** [comment]
resolved, thanks!
