### ISSUE TITLE
Error Hiding Classes Created By SDS

### ISSUE THREAD

**Issue by pkohrt** [MicrosoftDocs/OfficeEDU#6]
When I run 
Get-UnifiedGroup -ResultSize Unlimited | ? {$_.Name -like "Section_*"} | Set-UnifiedGroup &lt;groupname&gt; -HiddenFromAddressListsEnabled $true
I get the error message the '&lt;' operator is reserved for future use.
What is the correct syntax for this command? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 453bb3dd-91b4-5e7c-31a1-e6c2b71fff76
* Version Independent ID: 556e1bd9-1be3-4ab9-647c-8a042cc828e9
* Content: [Post Deployment Tasks for School Data Sync](https://docs.microsoft.com/en-us/schooldatasync/school-data-sync-post-deployment-tasks)
* Content Source: [SchoolDataSync/school-data-sync-post-deployment-tasks.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/SchoolDataSync/school-data-sync-post-deployment-tasks.md)
* Service: **school-data-sync**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by LaurenMoynihan** [comment]
I updated the string so please try it again. Also, please see this link. https://github.com/OfficeDev/O365-EDU-Tools/blob/master/SDS%20Scripts/Set-All_Sections_as_Hidden.ps1

**Comment by DanBaumgartner** [comment]
Closing issue because of time since last comment.
