### ISSUE TITLE
Provide additional options

### ISSUE THREAD

**Issue by DeanGross** [MicrosoftDocs/OfficeEDU#9]
Licenses can be assigned in the O365 or by using Azure AD Group bases licensing. Please provide information about these options also

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ddc00bca-f247-11e9-c187-987390e8b67e
* Version Independent ID: 8c6c03f0-2172-2ed0-f540-b047617726f5
* Content: [License Users](https://docs.microsoft.com/en-us/microsoft-365/education/deploy/license-users)
* Content Source: [M365Education/deploy/license-users.md](https://github.com/MicrosoftDocs/OfficeEDU-pr/blob/live/M365Education/deploy/license-users.md)
* Service: **microsoft-365-education**
* GitHub Login: @laurenm
* Microsoft Alias: **laurenm**

**Comment by DanBaumgartner** [comment]
Hello @DeanGross. My apologies about the delayed response. The M365 Education repro is currently unmanaged. I will see who I can reach out to about updating this information.
As the repro is currently unmanaged I will be closing this feedback.
